### PR TITLE
Addressable getFrontendFields issues 

### PR DESCRIPTION
**Pull request by phyzical**
I have not updated any tests, i cant seem to successfully run them.

if you know of a quick guide to running the tests ill give it a shot to make sure nothing is broken 
 
https://github.com/symbiote/silverstripe-addressable/issues/60

I understand this was trying to avoid overriding existing fields but i never receive the fields this solution's would simply add or override.

unless you guys can think of a better way to handle this?

### CODE REVIEW

**Comment by stephenmcm** [comment]
Hi @phyzical 
Someone will need to spin the code up to have a look, from what I can see it is a bug and should be returning the addressable fields but I'm not super familiar with this part of the module.

If no one has looked at this in a week or so give us a nudge and I'll work something out.

**Comment by phyzical** [comment]
sorry maybe i should clarify incase someone misinterprets ,

i get all the fields how it is, but they all come in as TextFields due to the explanation in  #60 rather than using the getAddressFields func with dropdowns ect.

**Comment by phyzical** [comment]
friendly bump :)

**Comment by phyzical** [comment]
one more bump <3

**Comment by phyzical** [comment]
another thing i've noticed, it works if the DataObject is new, ie not written, but when its called on an existing object this bug occurs?

**Comment by nglasl** [comment]
Thanks for bumping this, @stephenmcm could you please have a look at this one? Just for future reference @phyzical, please ping someone directly as it's easy to miss notifications when a pull request or issue isn't marked as _watching_ :)

Also, are you okay with me closing the issue while this pull request remains open? I'm keen to keep all the conversations in a single thread so it's easy to follow.

**Comment by nglasl** [comment]
@stephenmcm another bump on this one.

**Comment by nglasl** [comment]
Apologies for this one taking so long, I've updated the assignment here in an effort to get things moving.

**Pull request merged**
